### ISSUE TITLE
need update

### ISSUE THREAD

**Issue by mabhishek7081** [nmanumr/node-gtk-boilerplate#5]
it's not working . need update

**Comment by nmanumr** [comment]
Can you please explain what you are trying to do, what you are expecting, and what is actually happening?

**Comment by nmanumr** [comment]
If you had a hard time installing ```node-gtk``` then please refer to the official docs of ```node-gtk``` here: https://github.com/romgrk/node-gtk#installing-and-building

**Comment by mabhishek7081** [comment]
i installed it easily but problem is it is not running at npm start and can't build flatpak too . please help!

**Comment by nmanumr** [comment]
What's the error you are facing??

**Comment by mabhishek7081** [comment]
1. well when i run ``` npm install ``` it throws maybe because in package.json it requires an older version of node-gtk. but if you change it to latest (0.4.0) it get fixed.

2. after install when i run ``` npm start ``` it throws following error
 
``` > node-gtk-boilerplate@1.0.0 start /home/abhishek/Projects/node-gtk-boilerplate
> node src/main.js

internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module './binding/node-v57-linux-x64/node_gtk.node'
Require stack:
- /home/abhishek/Projects/node-gtk-boilerplate/lib/native.js
- /home/abhishek/Projects/node-gtk-boilerplate/lib/index.js
- /home/abhishek/Projects/node-gtk-boilerplate/src/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/home/abhishek/Projects/node-gtk-boilerplate/lib/native.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/abhishek/Projects/node-gtk-boilerplate/lib/native.js',
    '/home/abhishek/Projects/node-gtk-boilerplate/lib/index.js',
    '/home/abhishek/Projects/node-gtk-boilerplate/src/main.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-gtk-boilerplate@1.0.0 start: `node src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-gtk-boilerplate@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/abhishek/.npm/_logs/2020-06-19T15_29_53_573Z-debug.log
```

3. i just got a question in ``` src/main.js ``` why are import gi from some whare else instead of node-gtk, just asking how it benifites .

BTW Thanks a lot from addressing my issue

**Comment by nmanumr** [comment]
> Why are import gi from some whare else instead of ```node-gtk```.

Apparently, It seems like I just copied ```node-gtk/lib``` from node_modules and pasted at the root of the project (named ```lib```). The only change I remember now is to replace the content of ```lib/native.js``` to directly import the ```node_gtk.node```.

Actually pkg wasn't compiling ```node_gtk.node``` to the final package (as this was dynamically imported). I know this not a good way, the way would be something like a simple script that can automate this whole process while compiling the bundle.

> When I run npm start it throws the following error:

To resolve this issue you need to copy node-gtk binding to lib folder this command can help:
```cp ./node_modules/node-gtk/lib/binding/[BINDING_VERSION]/node_gtk.node ./lib/binding/```

I also updated the readme file, dependency versions, and binding path in ```lib/native.js```.

Let me known if you still face any issue regarding this boilerplate so that I can help.

**Comment by actuallyabhi** [comment]
It got fixed ! Flatpak is wroking now :)
